title: Shab Design
logo: /assets/images/Logo_Brown-02.svg
baseurl: /awesome-jekyll-theme
markdown: kramdown
author:
  name: Shabrina
  email: shabrina.m13@gmail.com
description: Aspiring UX Researcher & Designer with a background in visual design and a growing passion for user-centered problem solving.
##
# Typewritter configuration.
# Feel free to disable if you don't like it.
##
typewriter_effect: true

##
# Collections configuration
##
collections:
  projects:
    output: true

##
# Contact Channels configuration
# Uncomment for enable. Available contact channels are email, github, telegram, stackoverflow, discord, mastodon.
# Please fell free to send a PR if you need a new one.
# DISABLE GITHUB setting it as an empty string: ""
# if false, then no contact channels will be display.
##
contact_channels_section: true
contact_channels:
  email: "shabrina.m13@gmail.com"
  github: "https://github.com/shabdesign"
  telegram: "https://t.me/shab_design"
  x: "https://x.com/bekwerja"
  # stackoverflow: "https://stackoverflow.com"
  # discord: "https://discord.com/"
  # mastodon: "https://lile.cl/"

##
# Plugins configuration
##
plugins:
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-polyglot
  - jekyll-postcss

postcss:
  cache: false

##
# Polyglot configuration
##
languages: ["en"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public"]
parallel_localization: true

##
# Archives configuration
##
jekyll-archives:
  enabled:
    - categories
  layout: blog
  permalinks:
    category: "/category/:name/"
